      name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_AMBITIOUS_DUNE_06FE62710 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "./tariff-ui"   # your UI folder
          output_location: "dist"       # Vite build output, relative to app_location
          api_location: ""              # DISABLE API build
          skip_api_build: true          # belt-and-suspenders: don't try to build functions

