# Build & deploy Spring Boot JAR to Azure Web App
name: Build and deploy JAR app to Azure Web App - logistics-demo-api

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: logistics-demo-api
  JAVA_VERSION: '17'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Sanity: show where we are and confirm pom.xml exists
      - name: Verify repo layout
        run: |
          pwd
          ls -la
          find . -maxdepth 3 -name "pom.xml" -print

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ env.JAVA_VERSION }}
          cache: maven

      - name: Make mvnw executable
        run: chmod +x mvnw

      - name: Build with Maven (skip tests)
        run: ./mvnw -B -DskipTests package

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: target/*.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: java-app
          path: app

      # OIDC login with your federated credentials (you already set these secrets)
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_B555E90C5D3847F3B816BDC0B8C7B9AC }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_60A82C1F1B8D42C690038C9AA18BF359 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_724F9222196D4DEB83A55A4184375540 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: 'Production'
          package: app/*.jar
